stages:
- name: clone
  steps:
  - sourceCodeConfig: {}
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/cubepaas
        ln -s `pwd` /go/src/github.com/cubepaas/devops-go
        cd /go/src/github.com/cubepaas/devops-go
        go build -o bin/hello-server
        go test -cover
        ls
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
